# bitbucket-pipelines.yml
# Bitbucket pipelines build script.
#
# Created by firstName lastName on date.
#
# pwa-starter
#
# Copyright © 2009-2021 United States Government as represented by
# the Program Manager of the DHA: Web and Mobile Technology Program Management Office.
# All Rights Reserved.
#
# Copyright © 2009-2021 Contributors. All Rights Reserved.
#
# THIS OPEN SOURCE AGREEMENT ("AGREEMENT") DEFINES THE RIGHTS OF USE,
# REPRODUCTION, DISTRIBUTION, MODIFICATION AND REDISTRIBUTION OF CERTAIN
# COMPUTER SOFTWARE ORIGINALLY RELEASED BY THE UNITED STATES GOVERNMENT
# AS REPRESENTED BY THE GOVERNMENT AGENCY LISTED BELOW ("GOVERNMENT AGENCY").
# THE UNITED STATES GOVERNMENT, AS REPRESENTED BY GOVERNMENT AGENCY, IS AN
# INTENDED THIRD-PARTY BENEFICIARY OF ALL SUBSEQUENT DISTRIBUTIONS OR
# REDISTRIBUTIONS OF THE SUBJECT SOFTWARE. ANYONE WHO USES, REPRODUCES,
# DISTRIBUTES, MODIFIES OR REDISTRIBUTES THE SUBJECT SOFTWARE, AS DEFINED
# HEREIN, OR ANY PART THEREOF, IS, BY THAT ACTION, ACCEPTING IN FULL THE
# RESPONSIBILITIES AND OBLIGATIONS CONTAINED IN THIS AGREEMENT.
#
# Government Agency: DHA: Web and Mobile Technology Program Management Office
# Government Agency Original Software Designation: pwa-starter
# Government Agency Original Software Title: pwa-starter
# User Registration Requested. Please send email
# with your contact information to: robert.a.kayl.civ@mail.mil
# Government Agency Point of Contact for Original Software - Program Manager: robert.a.kayl.civ@mail.mil

image: node:12

pipelines:
  default:
    - step:
        name: "Install dependencies"
        caches:
          - node
        script:
          - npm install
    - step:
        name: "Build"
        caches:
          - node
        script:
          - npm run build
